import Head from 'next/head';
import Image from 'next/image';
/* import styles from '../styles/responsive.css'; */

export default function Home() {
  return (
    <>
      <Head>
        <title>sRoleplay Web App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <p>test</p>
    </>
  )
}
